CommercialApp/Controllers/SaleController.cs
using CommercialApp.Data;
using CommercialApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CommercialApp.Controllers
{
    public class SaleController : Controller
    {
        private readonly AppDbContext _context;

        public SaleController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var sales = _context.SaleTransactions
                .Include(x=>x.Products)
                .Include(x=>x.CustomerAccounts)
                .Include(x=>x.Employees)
                .ToList();
            if (sales == null)
                return View(new List<SaleTransaction>());
            return View(sales);
        }
        public IActionResult CreateSale()
        {
            var products = _context.Products.Select(p => new { p.Id, p.Name }).ToList();
            
            var customerAccounts = _context.CustomerAccounts
                .Select(ca => new { ca.Id, FullName = ca.Name + " " + ca.Surname }).ToList();
            
            var employees = _context.Employees
                .Select(e => new { e.Id, FullName = e.Name + " " + e.Surname }).ToList();

            ViewBag.Prods = new SelectList(products, "Id", "Name");
            ViewBag.CustomerAccs = new SelectList(customerAccounts, "Id", "FullName");
            ViewBag.Employees = new SelectList(employees, "Id", "FullName");
            return View();
        }

        [HttpPost]
        public IActionResult CreateSale(SaleTransaction sale)
        {
            sale.TransactionDate = sale.TransactionDate.ToUniversalTime();

            _context.SaleTransactions.Add(sale);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult UpdateSale(int id)
        {
            var sal = _context.SaleTransactions.Find(id);
            if (sal == null)
                return NotFound();

            var products = _context.Products.Select(p => new { p.Id, p.Name }).ToList();
            var customerAccounts = _context.CustomerAccounts
                .Select(ca => new { ca.Id, FullName = ca.Name + " " + ca.Surname }).ToList();
            var employees = _context.Employees
                .Select(e => new { e.Id, FullName = e.Name + " " + e.Surname }).ToList();

            ViewBag.Products = new SelectList(products, "Id", "Name");
            ViewBag.CustomerAccs = new SelectList(customerAccounts, "Id", "FullName");
            ViewBag.Employees = new SelectList(employees, "Id", "FullName");

            return View(sal);
        }

        [HttpPost]
        public IActionResult UpdateSale(SaleTransaction sale)
        {
            var sal = _context.SaleTransactions.Find(sale.Id);
            sal.ProductsId = sale.ProductsId;
            sal.Quantity = sale.Quantity;
            sal.Price = sale.Price;
            sal.TotalAmount = sale.TotalAmount;
            sal.CustomerAccountsId = sale.CustomerAccountsId;
            sal.EmployeesId = sale.EmployeesId;
            sal.TransactionDate = sale.TransactionDate.ToUniversalTime();
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Details(int id)
        {
            var det = _context.SaleTransactions.Where(x => x.Id == id)
                .Include(x=>x.Products)
                .Include(x=>x.CustomerAccounts)
                .Include(x=>x.Employees)
                .ToList();

            return View(det);
        }
    }
}

CommercialApp/Views/Sale/CreateSale.cshtml
@model CommercialApp.Models.SaleTransaction

@{
    ViewData["Title"] = "CreateSale";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Satış Yap</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateSale">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductsId" class="control-label">Ürün</label>
                <select asp-for="ProductsId" class="form-control" asp-items="ViewBag.Prods"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label">Adet</label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Fiyat</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount" class="control-label">Toplam Tutar</label>
                <input asp-for="TotalAmount" class="form-control" />
                <span asp-validation-for="TotalAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerAccountsId" class="control-label">Cari</label>
                <select asp-for="CustomerAccountsId" class="form-control" asp-items="ViewBag.CustomerAccs"></select>
            </div>
            <div class="form-group">
                <label asp-for="EmployeesId" class="control-label">Personel</label>
                <select asp-for="EmployeesId" class="form-control" asp-items="ViewBag.Employees"></select>
            </div>
            <div class="form-group">
                <label asp-for="TransactionDate" class="control-label">İşlem Tarihi</label>
                <input asp-for="TransactionDate" class="form-control" />
                <span asp-validation-for="TransactionDate" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri dön</a>
</div>

CommercialApp/Views/Sale/Details.cshtml
@model List<SaleTransaction>

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<hr />

<h1>Satış Detayları</h1>

<hr />

<table class="table table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Satış Id</th>
            <th>Ürün</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam Tutar</th>
            <th>Cari</th>
            <th>Personel</th>
            <th>Tarih</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var sale in Model)
        {
            <tr>
                <td>@sale.Id</td>
                <td>@sale.Products.Name</td>
                <td>@sale.Quantity</td>
                <td>@sale.Price</td>
                <td>@sale.TotalAmount</td>
                <td>@sale.CustomerAccounts.Name @sale.CustomerAccounts.Surname</td>
                <td>@sale.Employees.Name @sale.Employees.Surname</td>
                <td>@sale.TransactionDate</td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Print" class="btn btn-dark">Yazdır</a>

CommercialApp/Views/Sale/Index.cshtml
@model List<SaleTransaction>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<table id="tblSaleIndex" class="table table-bordered" style="margin-top:20px">
    <thead>
        <tr>
            <td>Id</td>
            <td>Ürün</td>
            <td>Cari</td>
            <td>Personel</td>
            <td>Adet</td>
            <td>Fiyat</td>
            <td>Toplam Tutar</td>
            <td>Tarih</td>
            <td>Detay</td>
            <td>Güncelle</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var sal in Model)
        {
            <tr>
                <td>@sal.Id</td>
                <td>@(sal.Products != null ? sal.Products.Name : "Ürün bilgisi yok")</td>
                <td>@(sal.CustomerAccounts != null ? sal.CustomerAccounts.Name + " " + sal.CustomerAccounts.Surname : "Cari bilgisi yok")</td>
                <td>@(sal.Employees != null ? sal.Employees.Name + " " + sal.Employees.Surname : "Personel bilgisi yok")</td>

                <td>@sal.Quantity</td>
                <td>@sal.Price</td>
                <td>@sal.TotalAmount</td>
                <td>@sal.TransactionDate</td>
                <td><a asp-action="Details" asp-controller="Sale" asp-route-id="@sal.Id" class="btn btn-info">Detay</a></td>
                <td><a asp-action="UpdateSale" asp-route-id="@sal.Id" class="btn btn-warning">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="CreateSale" class="btn btn-primary">Satış Yap</a>



@* <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#tblSaleIndex').dataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/2.1.4/sorting/turkish-string.js"
        }
    });
</script> *@


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>



<script>

    $('#tblSaleIndex').dataTable({

        "responsive": true,

        "dom": '<"html5buttons"B>lTfgitp',

        "language": {

            "emptyTable": "Gösterilecek ver yok.",

            "processing": "Veriler yükleniyor",

            "sDecimal": ".",

            "sInfo": "_TOTAL_ kayıttan _START_ - _END_ arasındaki kayıtlar gösteriliyor",

            "sInfoFiltered": "(_MAX_ kayıt içerisinden bulunan)",

            "sInfoPostFix": "",

            "sInfoThousands": ".",

            "sLengthMenu": "Sayfada _MENU_ kayıt göster",

            "sLoadingRecords": "Yükleniyor...",

            "sSearch": "Ara:",

            "sZeroRecords": "Eşleşen kayıt bulunamadı",

            "oPaginate": {

                "sFirst": "İlk",

                "sLast": "Son",

                "sNext": "Sonraki",

                "sPrevious": "Önceki"

            },

            "oAria": {

                "sSortAscending": ": artan sütun sıralamasını aktifleştir",

                "sSortDescending": ": azalan sütun sıralamasını aktifleştir"

            },

            "select": {

                "rows": {

                    "_": "%d kayıt seçildi",

                    "0": "",

                    "1": "1 kayıt seçildi"

                }

            }

        }

    });

</script>

CommercialApp/Views/Sale/UpdateSale.cshtml
@model CommercialApp.Models.SaleTransaction

@{
    ViewData["Title"] = "UpdateSale";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Satış Güncelle</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("UpdateSale", "Sale", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.Id)
            <div class="form-group">
                @Html.LabelFor(x => x.Quantity, "Adet")
                @Html.TextBoxFor(x => x.Quantity, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Price, "Fiyat")
                @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.TotalAmount, "Toplam Tutar")
                @Html.TextBoxFor(x => x.TotalAmount, new { @class = "form-control" })
            </div>
            
            @* <div class="form-group">
                @Html.LabelFor(x => x.TransactionDate)
                @Html.TextBoxFor(x => x.TransactionDate, new { @class = "form-control" })
            </div> *@

            <button class="btn btn-warning">Güncelle</button>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Geri dön</a>
</div>